# Generated by Django 3.1.5 on 2021-01-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
